appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: Ljn0tC/vgQwYlG59jDGEIdtwiKeYclxkQHGEyoaLdhU0DpDYudjlFIgA2jiiiOa52ws+9DiKZ/0njyhIn/aM0GhZFmJtp7jma04iRG1zb7odBhgmdw/zjqigwEQJcRCTnvtiUy4EU+s5PCDmE7ltQVecnJdkGbg1fKVK9WqWujoPfDD4aWUr5QWMAuh0LK0yHzWiL6y2MEY0fF5c9yPpP76lv1nbJCfIslvgyDYczbAbR2/1CcV1i4NHH6H/j74jadrPFmduITxBLuRy5Q+dcpPCV71hE8SmXQwL5Zp/XDg8nyo6EIWqjzP53NeuDs1mY9AyYAYt4FHz0tmeeKUOkbP6V5qOYwxGTUlpzIj7nI4tzb7rrllBNMoM5ea1OkP1pHmo6RdDnl2tneAxgBEaErK+G+AmjBjK0lWVctY8GE9lYTiUeRYPoaAeeuIwLtSELeWWun8EQJ5qkvATyIaQPBMxnCc+paLemvEjd0/Cj63bKrJowTNuVAXe0KuiSBdg2+ui9bqlTkPUIsdNi3kMf1/1mWYrutg2jOoa/ODYAJfQDZ/v06Hj1FFxFbXlPEqgyCn6PZXB9a3AdbZFGdbYa6e4+shIGJ2ovF+k+niUYlLhDXVnNRsDgM+ES4dFgWk8lmIGZs3lpcQgtGmNc/leOh8eQu1eQrtWGio2S++23Xg=
conda_forge_output_validation: false
